### PR TITLE
Update linux installation command from termscp.veeso.dev/get-started.…

### PR DESCRIPTION
**Pull request by piradata**
just a simple readme update

### CODE REVIEW

**Review by veeso — CHANGES_REQUESTED** [review]
the command works

**Comment by piradata** [comment]
old url does not loads here

**Comment by veeso** [comment]
the dns record is configured correctly, the url works. If you want keep both the urls

**Comment by piradata** [comment]
Screenshot_20231109-215033

i think the problrm is because you are using a .dev domain without a valid ssl certificate, i also have a dev domain and it requires one to be accessible via browser

**Review by veeso — APPROVED** [review]

**Pull request merged**
