### PR TITLE
Add NetBSD

### PR DESCRIPTION
**Pull request by 0323pin**
## Description

I've packaged `termscp` for NetBSD and I'm planning to merge the package within a day or two. An official pre-compiled binary should be available for users by early next week.

List here your changes

- Update README.md

### CODE REVIEW

**Review by veeso — APPROVED** [review]
That's good! Please, tell me whenever the package is ready to be installed, so I can merge your PR

**Comment by 0323pin** [comment]
> That's good! Please, tell me whenever the package is ready to be installed, so I can merge your PR

No problem. I'll post here when things are ready.

**Comment by 0323pin** [comment]
@veeso One step closer, tests seem fine 😄 

2022-10-20-163928_1366x768_scrot

2022-10-20-164048_1366x768_scrot

**Comment by 0323pin** [comment]
@veeso Merged now, https://mail-index.netbsd.org/pkgsrc-changes/2022/10/21/msg262339.html

Give it a few days and binaries will become available.

**Comment by 0323pin** [comment]
@veeso thanks. Just checked and the first binaries are now available for x86_64 😄

**Pull request merged**
